theme: minima
title: Barb H-S
author: dagny099
email: dagny099@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my new site! Barb, this description will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dagny099 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
